name: Android CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: List APK files
      run: ls -R app/build/outputs/apk/release/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: app
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v4.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag }}-new
        release_name: Release ${{ github.event.inputs.tag }}-new
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v4.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: KeyBroad_cn_unsigned-${{ github.event.inputs.tag }}.apk
        asset_content_type: application/zip
