name: Android CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: List APK files
      run: ls -R app/build/outputs/apk/release/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: app
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false

    - name: rename
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/KeyBroad-cn_unsigned-${{ github.event.inputs.tag }}.apk
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: | 
          app/build/outputs/apk/release/KeyBroad-cn_unsigned-${{ github.event.inputs.tag }}.apk

          generate_release_notes: true
